### ISSUE TITLE
Frequency setting

### ISSUE THREAD

**Issue by M0XFX** [TriodeGirl/Arduino-UNO-R4-Minima-Fast-DAC#1]
Hi, I am sorry to pester you as am sure you have better thing to do. 

I have been playing around with (Arduino_UNO_R4_DAC_sine_wave_FPU_1a.ino) as I am trying to produce a reasonably clean sine wave between 50 and 200Hz for radio communications from the R4 board.

There is seems to be very little in the way of libraries for the R4 DAC and the analogWave.h gives a very broken wave form.

The code runs extremely well and the sine wave is clean enough for my project, however I am unable to set the frequency it seems stuck at around 350Hz. 

I have try changing the value at (float sine_frequency =  100.0;    // Desired frequency) which does not seem to make any difference. Changing the delta point does make a difference to the frequency but I don't understand the correlation between the values.

Is there something I am missing?

Thank you an advance for you help.

Kind regards John M0XFX

Love the name BTW.

**Comment by M0XFX** [comment]
I have figured it out, adjusting the sample timings adjusts the frequency. Although this sketch gives much finer resolution at low frequency as opposed to the " analogWave.h" library, the timings become unstable if you are using multiple interrupts for other tasks, but that's what is mentioned.  Still it's an impressive bit of code for the R4 none the less.

**Comment by TriodeGirl** [comment]
Hopefully soon, I will get around to doing a proper program to do this, with the AGT0 mS timer repurposed.
This code example was only meant to explore how fast one could use the DAC and do something useful.
Thanks.
